CREATE TABLE NOMNOM (
    NAME TEXT,
    NEIGHBOURHOOD TEXT,
    CUISINE TEXT,
    REVIEW REAL,
    PRICE TEXT,
    HEALTH TEXT
);

INSERT INTO NOMNOM(NAME, NEIGHBOURHOOD, CUISINE, REVIEW, PRICE, HEALTH)VALUES
('PETER','BROOKLYN','STEAK',4.4,'$$$$','A'),
('JONGRO','MIDTOWN','KOREAN',3.5,'$$','A'),
('POCHA','MIDTOWN','PIZZA',4,'$$$','B'),
('LIGHTHOUSE','QUEENS','CHINESE',3.9,'$','A'),
('MINCA','DOWNTOWN','AMERICAN',4.6,'$$$',''),
('MAREA','CHINATOWN','CHINESE',3.0,'$$$$',''),
('DIRTY CANDY','UPTOWN','ITALIAN',4.9,'$$','B'),
('DI FARA PIZZA','BROOKLYN','PIZZA',3.8,'$$$','A'),
('GOLDEN UNICORN','UPTOWN','ITALIAN',3.8,'$$','A');

SELECT * FROM NOMNOM;

SELECT DISTINCT NEIGHBOURHOOD FROM NOMNOM;

SELECT DISTINCT CUISINE FROM NOMNOM;

SELECT * FROM NOMNOM WHERE CUISINE = 'CHINESE';

SELECT * FROM NOMNOM WHERE REVIEW >=4;

SELECT * FROM NOMNOM WHERE CUISINE = 'ITALIAN' AND PRICE = '$$';

SELECT * FROM NOMNOM WHERE NAME LIKE '%CANDY%';

SELECT * FROM NOMNOM
WHERE NEIGHBOURHOOD IN ('MIDTOWN','UPTOWN','CHINATOWN');

SELECT * FROM NOMNOM ORDER BY REVIEW DESC LIMIT 4;