CREATE TABLE MARKS(
    STUDENT_NAME TEXT,
    STUDENT_ID REAL,
    STUDENT_MARKS REAL
);

INSERT INTO MARKS(STUDENT_NAME, STUDENT_ID, STUDENT_MARKS)VALUES
('Ayesha',1239650, 29),
('Umaimah', 0987654, 99),
('Khadija', 68754321, 72),
('Fatima', 56784321, 88);

SELECT COUNT(STUDENT_MARKS) AS marks
FROM MARKS;

SELECT AVG(STUDENT_MARKS) AS Average_Marks
FROM MARKS;

SELECT SUM(STUDENT_MARKS) AS Total_Marks
FROM MARKS;