CREATE TABLE PRODUCTS1(
PRODUCT_ID TEXT,
PRODUCT_NAME TEXT,
SUPPLIER_ID TEXT,
CATEGORY_ID TEXT,
UNIT TEXT,
PRICE REAL
);

INSERT INTO PRODUCTS1( PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT, PRICE) VALUES
('1', 'chais', '1','1', '10 boxes*20 bags',18),
('2', 'chang', '1','1', '24-12 OZ BOTTLES',19),
('3', 'aniseed syrup', '1','2', '12-550 ML BOTTLES',10),
('4', 'chef anton seasoning', '2','2', '48-6 OZ JARS',22),
('5', 'chef anton mix', '2','2', '36 BOXES',21.35);

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS1;

SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS1;

SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS1;